# Introduction to tensor

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

1.12.1+cu113


## Creating Tensors

### torch.tensor()

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# dimension of tensor
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Metrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]], 
                       [[1,2,3], 
                        [4,5,3], 
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]],

        [[1, 2, 3],
         [4, 5, 3],
         [7, 8, 9]]])

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

### Random tensor

In [ ]:
# Create Random Tensors of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4983, 0.9108, 0.2989, 0.4659],
        [0.1992, 0.8608, 0.5701, 0.9387],
        [0.6727, 0.6234, 0.7634, 0.8280]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_img = torch.rand(size=(224,224,3))
random_img

In [ ]:
random_img.shape

torch.Size([224, 224, 3])

In [ ]:
random_img.ndim

3

### One's and zero's

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))

In [ ]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Range of tensors

In [ ]:
# Use torch.range
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Create tensor like another tensors 
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatype

**Note:** While dealing with tensors, deep learning, 3 big errors you might face with data
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float32 
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # datatype of the tensors
                               device=None, # device (cpu, gpu)
                               requires_grad=False) # wheather or not to track gradient
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# float 32 to float 16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

## Getting information from tensors (Tensor attributes)

1. Tensors not right datatype? check `tensor.dtype`
2. Tensors not right shape? check `tensor.shape`
3. Tensors not on the right device? check `tensor.device`

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4969, 0.5835, 0.8044, 0.4821],
        [0.3704, 0.6388, 0.4110, 0.9030],
        [0.0192, 0.3486, 0.6971, 0.9471]])

In [ ]:
print(f"Data type: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device running: {some_tensor.device}")

Data type: torch.float32
Shape of tensor: torch.Size([3, 4])
Device running: cpu


# Manipulating tensors (Tensor operation)
Tensor operation includes
* Addition
* Subtraction
* Multiplication (Element wise)
* Division (Element wise)
* Matrix multiplication

## Basic operation (+,-,x,/)

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
# addition
tensor, tensor+10

(tensor([1, 2, 3]), tensor([11, 12, 13]))

In [ ]:
# multiplication
tensor*10

tensor([10, 20, 30])

In [ ]:
# subtraction
tensor-10

tensor([-9, -8, -7])

In [ ]:
# try out pytorch in-built function (multiplication)
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, torch.tensor([2,3,4])), tensor

(tensor([3, 5, 7]), tensor([1, 2, 3]))

## Matrix multiplication

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print("Equals: ", tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

There are two rules while doing matrix multiplication
1. Inner dimension must be matched e.g. `(k, m) (m,l)` will work
2. The resulting metrix has the size of outer dimension `(k, m) (m,l) = (k,l)`

In [ ]:
torch.matmul(torch.rand(3,4), torch.rand(4,2))

tensor([[1.0309, 1.9349],
        [1.3814, 2.3840],
        [0.4889, 1.0328]])

**Shape error**

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
# torch.mm is short for torch.matmul
torch.mm(tensor_A, tensor_B)

RuntimeError: ignored

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
# To fix tensor shape issues we can manipulate shape of one of tensor using transpose (swith shape)
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]), torch.Size([3, 2]))

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# Aggregation

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## min, max, mean, sum etc

In [ ]:
# min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# mean
x.mean()

RuntimeError: ignored

In [ ]:
# error solved by changing datatype
x.type(torch.float32).mean(), torch.mean(x.type(torch.float32))

(tensor(45.), tensor(45.))

In [ ]:
# sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## argmin, argmax

In [ ]:
# argmin
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [ ]:
# argmax
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [ ]:
x[x.argmin()] == x[0]

tensor(True)

In [ ]:
x[x.argmax()]

tensor(90)

# Reshaping, viewing, stacking, squeezing, unsqueezing and permute

* **Reshaping** - reshape a tensor to a defined shape
* **View** - Return a view of an input tensor with a defined shape
* **Stacking** - Combine multiple tensor
* **Squeezing** - Removes all `1` dimensions from a tensor
* **Unsqueezing** - add a `1` dimension to a target tensor
* **Permute** - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# create a tensor
x = torch.arange(1., 28.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.]),
 torch.Size([27]))

## Reshape

In [ ]:
# Reshape (add an extra dimension) - shape must be matched with element
x_reshaped = x.reshape(3,3,3)
x_reshaped, x_reshaped.shape

(tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],
 
         [[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]],
 
         [[19., 20., 21.],
          [22., 23., 24.],
          [25., 26., 27.]]]), torch.Size([3, 3, 3]))

## View

In [ ]:
# view
z = x.view(3,3,3)
z, z.shape

(tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],
 
         [[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]],
 
         [[19., 20., 21.],
          [22., 23., 24.],
          [25., 26., 27.]]]), torch.Size([3, 3, 3]))

In [ ]:
z = z.reshape(1,27)
# changing z
z[:, 0 ] = 40
# changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z, x

(tensor([[40.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
          15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.]]),
 tensor([40.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.]))

## Stack

In [ ]:
# Stack - torch.stack(stacking_tensors, on_dimension=0,1,2...)
x_stacked = torch.stack([x,x], dim=0)
x_stacked

tensor([[40.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.],
        [40.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.]])

## Squeezing and unsqueezing

In [ ]:
# squeezing and unsqueezing
x_reshaped = x_reshaped.reshape(1,1,27)
x_reshaped, x_reshaped.shape

(tensor([[[40.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
           15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.]]]),
 torch.Size([1, 1, 27]))

In [ ]:
# Removed all single dimension
x_squeezed = x_reshaped.squeeze() 
x_squeezed, x_squeezed.shape

(tensor([40.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.]),
 torch.Size([27]))

In [ ]:
# Add single dimension
print("Squeezed tensor shape: ", x_squeezed.shape)
x_unsqueezed = x_squeezed.unsqueeze(dim=0) # dimension 0, so 1 will be added in first dimension e.g.(1,27)
print("Unsqueezed tensor shape: ", x_unsqueezed.shape)
print("The unsqueezed tensor: ", x_unsqueezed)

Squeezed tensor shape:  torch.Size([27])
Unsqueezed tensor shape:  torch.Size([1, 27])
The unsqueezed tensor:  tensor([[40.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.]])


## Permute

In [ ]:
# Return a view of the input with dimensions permuted (swapped) in a certain way
x_original = torch.randn(224,224,3) # [height, width, color_channels]
x_original.size()

torch.Size([224, 224, 3])

In [ ]:
# permute dimension in a certain way
# color_channels was at 2nd, we put it at 0th
# height was at 0th, we put it into 1st
# width was at 1st, we put it to 2nd
x_permuted = x_original.permute(2,0,1) # [color_channels, height, width]
x_permuted.shape

torch.Size([3, 224, 224])

# Selecting data (indexing)

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][2]

tensor(3)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# : to select all of the target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# get all values of 0th and 1st dimensions but only index 1 in second dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# get all values of 0th dimension, but only the 1st index value of 1st and 2nd dimension
x[:, 1,1]

tensor([5])

In [ ]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# last column
x[0,:,2]

tensor([3, 6, 9])

# Pytorch and Numpy

In [ ]:
array = np.arange(1.0,9.0)
tensor = torch.arange(1.0, 9.0)

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [ ]:
tensor_from_array = torch.from_numpy(array) # pytorch reflect numpy default datatype of float64
tensor_from_array

tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)

In [ ]:
tensor_from_array.type(torch.float32).dtype

torch.float32

In [ ]:
array, tensor_from_array

(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [ ]:
# Changing the value of array doesn't change the value of tensor and vice-versa
array = array+1
array, tensor_from_array

(array([2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [ ]:
tensor_from_array +=1 
tensor_from_array, array

(tensor([2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64),
 array([2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# tensor to numpy array - numpy is copying the dtype of tensor
tensor = torch.ones(7)
numpy_from_tensor = tensor.numpy()
tensor, numpy_from_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# tensor and numpy are compatible in operation if converted
tensor + numpy_from_tensor

tensor([2., 2., 2., 2., 2., 2., 2.])

In [ ]:
array, tensor

(array([2., 3., 4., 5., 6., 7., 8., 9.]), tensor([1., 1., 1., 1., 1., 1., 1.]))

In [ ]:
a = np.ones(7)
b = torch.ones(7)
a, b

(array([1., 1., 1., 1., 1., 1., 1.]), tensor([1., 1., 1., 1., 1., 1., 1.]))

In [ ]:
a+b.numpy()

array([2., 2., 2., 2., 2., 2., 2.])

# Reproducibility
Trying to take random out of random
`random seed`

In [ ]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2170, 0.9059, 0.1948, 0.4234],
        [0.9703, 0.2989, 0.0322, 0.0875],
        [0.9855, 0.6798, 0.0912, 0.8235]])
tensor([[0.8978, 0.4398, 0.0195, 0.4563],
        [0.7968, 0.4701, 0.5416, 0.0417],
        [0.0477, 0.0482, 0.6183, 0.3405]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
import torch

RANDOM_SEED = 14
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.5695, 0.0047, 0.9303, 0.7257],
        [0.8295, 0.7683, 0.0600, 0.1453],
        [0.2924, 0.5292, 0.1466, 0.8305]])
tensor([[0.5695, 0.0047, 0.9303, 0.7257],
        [0.8295, 0.7683, 0.0600, 0.1453],
        [0.2924, 0.5292, 0.1466, 0.8305]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Access to GPU

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
!nvidia-smi

Tue Aug 16 07:45:40 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# Set device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of GPU
torch.cuda.device_count()

1